#

namespace import -force msgcat::mcset

mcset nl Help Hulp 
#mcset nl Cancel Abbruch
mcset nl Quit {Houd met op}
mcset nl Exit Uitgang
#mcset nl Next Weiter
#mcset nl Action Aktion
#mcset nl Actions Aktionen 
#mcset nl actions Aktionen
#mcset nl Reports Berichte
mcset nl Preferences Voorkeur
#mcset nl Open... Öffnen
#mcset nl Pause Anhalten
#mcset nl Resume Fortfahren
#mcset nl {Add/Edit Log} {Log Hinzufügen/Ändern}
#mcset nl Add... Hinzufügen...
#mcset nl View Ansicht
#mcset nl Complete Abschließen
#mcset nl Activate Aktivieren
#mcset nl {Abort Active} {Abbruch Aktiv}
#mcset nl {Abort Pending} {Abbruch Wartend}
#mcset nl Abort Abbrechen
#mcset nl Reactivate Reaktivieren
#mcset nl Projects Projekte
#mcset nl Add Hinzufügen
#mcset nl Edit Bearbeiten
#mcset nl About Über
#mcset nl {Please select the date of log} {Bitte das Datum für Logeinträge auswählen,}
#mcset nl {entries to be input or edited} {die bearbeitet oder neu eingegeben werden sollen}
#mcset nl {Input and editing of log entries} {Eingabe und Bearbeitung von Logeinträgen}
#mcset nl "Log edit" Log-Bearbeitung
#mcset nl "Date selection" "Datumauswahl"
#mcset nl "No date selected" "Kein Datum ausgewählt"
#mcset nl "Invalid date format" "Ungültiges Datumsformat"
#mcset nl "Editing of log file" "Bearbeitung einer Log-Datei"
mcset nl Day Jour
mcset nl day jour
mcset nl days jours
#mcset nl week Woche
#mcset nl "Import of log entries" "Import von Logeinträgen"
#mcset nl File Datei
#mcset nl {No entries found in file} {Keine Einträge gefunden in Datei}
#mcset nl "Import all" "Alles"
#mcset nl Import Importieren
#mcset nl Project Projekt
#mcset nl "End " Ende
#mcset nl End Ende
#mcset nl Delete Löschen
#mcset nl "Edit log entry" "Bearbeitung eines Log-Eintrages"
#mcset nl "Add a new entry" "Neuer Log-Eintrag"
#mcset nl {Start Time} Startzeit
#mcset nl {End Time} Ende
#mcset nl {ActionTitle} {Titel der Aktion}
#mcset nl Activity Aktivität
#mcset nl Contact Kontakt
#mcset nl Contacts Kontakte
#mcset nl Save Speichern
#mcset nl "Save As..." "Speichern unter..."
#mcset nl Description Beschreibung
#mcset nl "Adjust to previous EndTime" "Zeit an vorheriges Ende anpassen"
#mcset nl "Adjust to following Startime" "An nächste Startzeit anpassen"
#mcset nl "Invalid date range" "Zeitbereich ungültig"
#mcset nl "The StartTime is greater\nthan the EndTime" "Startzeit größer als Endzeit"
#mcset nl "Invalid date" "Ungültiges Datum"
#mcset nl {Please enter a value for} {Bitte einen Wert eingeben für:}
#mcset nl {is not a valid\ntime value for} {ist keine gültige\nZeit für Tag}
#mcset nl "There are overlapping (marked with '>')\nand inconsistent (marked with '!') time ranges." "Es existieren überlappende ('>')\nund inkonsistente '(!)' Zeitbereiche."
#mcset nl "There are overlapping time ranges (marked with '>')." "Es existieren überlappende Zeitbereiche."
#mcset nl "There are inconsistent time ranges (marked with '!')." "Es existieren inkonsistente Zeitbereiche."
#mcset nl {Do you want to save?} {Wollen Sie trotzdem abspeichern?}
#mcset nl "Weekly time bookings by project" "Projekte: Wöchentliche Zeitbuchungen"
#mcset nl "Time by activity" "Gesamtzeit je Aktivität"
#mcset nl "Total time for a project" "Gesamtzeit für ein Projekt"
#mcset nl "Project Progress Report" "Projektfortschritt"
#mcset nl Directory Verzeichnis
#mcset nl "Current Directory" "Aktuelles Verzeichnis"
#mcset nl "File name :" "Dateiname:"
#mcset nl "Save Text" "Speichern als Text"
#mcset nl "Save HTML" "Speichern als HTML"
#mcset nl "Save HTML..." "Speichern als HTML ..."
#mcset nl "Description contains" "Beschreibung enthält"
#mcset nl "Documentation Directory" "Dokumentationsverzeichnis"
#mcset nl "Data directory root" "Wurzelverzeichnis für Daten"
#mcset nl Language Sprache
#mcset nl "Hours Worked per Day (decimal)" "Arbeitsstunden pro Tag (dezimal)"
#mcset nl "Date Format" Datumsformat
#mcset nl "European (DD/MM/YYYY)" "Europäisch (DD/MM/YYYY)"
#mcset nl "American (MM/DD/YYYY)" "Amerikanisch (MM/DD/YYYY)"
#mcset nl "History Window Depth" {Zeilen für Historien-Fenster}
#mcset nl "Current Window Depth" "Zeilen für Log-Fenster"
#mcset nl "Number of 'Today' actions" "Anzahl der 'Heute'-Aktionen"
#mcset nl Prefix Präfix
#mcset nl "SMTP Preferences filename" "Dateiname für SMTP-Einstellungen"
#mcset nl "email address" "EMail-Adresse"
#mcset nl traditional traditionell
#mcset nl "local mail submission port" "lokaler Mail-Port"
#mcset nl "Input an action" "Eingabe einer Aktion"
#mcset nl {Edit action} "Bearbeite Aktion"
#mcset nl Title Titel
#mcset nl Date Datum
#mcset nl Priority Priorität
#mcset nl Expected-cost "Erwartete Kosten"
#mcset nl Expected-time "Erwartete Zeit"
#mcset nl Expected-Time "Erwartete Zeit"
#mcset nl Revised-expected-time "Geänd. Erwartete Zeit"
#mcset nl Expected-start-date "Erwartete Startzeit"
#mcset nl Completed-date "Fertigstellungsdatum"
#mcset nl Active-date "Aktivierungsdatum"
#mcset nl Aborted-date "Abbruchdatum"
#mcset nl Expected-completed-date "Erw-Fertigstellungsdatum"
#mcset nl Expected-Completed-Date "Erw-Fertigstellungsdatum"
#mcset nl Revised-expected-completed-date "Geänd. Erw-Fertigstellungsdatum"
#mcset nl Revised-date Geänd-Datum
#mcset nl Precursor Vorgänger
#mcset nl Active-after "Aktiv nach"
#mcset nl Subtask-of "Unteraufgabe von"
#mcset nl Next-action "Nächste Aktion"
#mcset nl Abort-action Abbruch-Aktion
#mcset nl Difficulty Schwierigkeit
#mcset nl nobrainer simpel
#mcset nl trivial trivial
#mcset nl easy leicht
#mcset nl tricky anspruchsvoll
#mcset nl hard schwer
#mcset nl "very hard" "sehr schwer"
#mcset nl Email-status-to "Sende-Status an"
#mcset nl Deliverable Auslieferbar
#mcset nl Reason Grund
#mcset nl Message Nachricht
#mcset nl "Mail to" "Sende an"
#mcset nl "Mail an action" "Sende eine Aktion"
#mcset nl "Add a new project" "Neues Projekt"
#mcset nl "Project name" Projektname
#mcset nl "Book as breaks" "Als Pause buchen"
#mcset nl "Book as overheads" "Als Overhead buchen"
#mcset nl "Booking Code" "Buchungs-Code"
#mcset nl "Start Date" "Startdatum"
#mcset nl "End Date" "Beendigungsdatum"
#mcset nl "Edit Projects" "Projekte bearbeiten"
#mcset nl Breaks Pausen
#mcset nl "Project Times" Projektzeiten
#mcset nl Total Gesamt
#mcset nl "Total (non breaks)" "Gesamt (ohne Pausen)"
#mcset nl Today Heute
#mcset nl "Select date range" "Zeitbereich"
#mcset nl "Enter Project details" Projektdetails
#mcset nl "Enter information for Project Progress Report" "Projektfortschritt"
#mcset nl "Select Time Period" "Auswahl der Zeitbereichs"
#mcset nl "Time Format" Zeitformat
#mcset nl "Decimal hours" "Stunden dezimal"
#mcset nl "Decimal days" "Tage dezimal"
#mcset nl "Spread overhead projects" "Overhead Projekte aufteilen"
#mcset nl "Book by Project" "Sortieren nach Projekt"
#mcset nl Year Jahr
#mcset nl weeks Wochen
#mcset nl "starting at number" "Start bei"
#mcset nl "Time by Activity" "Gesamtzeit je Aktivität"
#mcset nl "Project Progress Report for" "Projektfortschrittsbericht für"
#mcset nl "Total Times for" "Gesamtzeit für"
#mcset nl "Time Bookings" "Zeitbuchungen"
mcset nl Sun "Dim"
mcset nl Mon "Lun"
mcset nl Tue "Mar"
mcset nl Wed "Mer"
mcset nl Thu "Jeu"
mcset nl Fri "Ven"
mcset nl Sat "Sam"
#mcset nl "Breaks total" "Pausen gesamt"
#mcset nl "Time Bookings for week" "Zeitbuchungen für Kalenderwoche"
#mcset nl  of von
#mcset nl "Warning - cant open" "Warnung - folgende Datei kann nicht geöffnet werden:" 
#mcset nl "Total time" Gesamtzeit
#mcset nl "Total time for" "Die Gesamtzeit für"
#mcset nl is ist
#mcset nl "decimal days" "dezimale Tage"
#mcset nl Examined "Untersucht wurden"
#mcset nl "files and found entries for" "Dateien. Gefunden wurden Einträge für"
#mcset nl "of them" "von ihnen"
#mcset nl "First date was" "Erstes Datum:"
#mcset nl "last date was" "Letztes Datum:"
#mcset nl "Adjust start time" "Startzeit anpassen" 
#mcset nl "Adjust start time back towards previous start time of" "Startzeit anpassen in Richtung auf vorherige Startzeit von"
#mcset nl "Adjust start time back towards the start of the day" "Startzeit an Tagesbeginn anpassen"
#mcset nl "Adjust previous end time" "Vorherige End-Zeit anpassen"
#mcset nl "New Start Time" "Neue Startzeit"
#mcset nl "Minutes to Subtract from StartTime" "Zu subtrahierende Minuten"
#mcset nl Set "Startzeit setzen"
#mcset nl calendar Kalender
#mcset nl Calendar Kalender
#mcset nl Su So
#mcset nl Tu Di
#mcset nl We Mi
#mcset nl Th Do
#mcset nl January Januar
#mcset nl February Februar
#mcset nl March März
#mcset nl April April
#mcset nl May Mai
#mcset nl June Juni
#mcset nl July Juli
#mcset nl August August
#mcset nl September September
#mcset nl October Oktober
#mcset nl November November
#mcset nl December Dezember
#mcset nl "Select Contacts to view" "Auswahl zum Anzeigen von Kontakten"
#mcset nl Forename Vorname
#mcset nl Phone Telefon
#mcset nl Type Typ
#mcset nl Surname Nachname
#mcset nl "Contacts Display" "Anzeige der Kontakte"
#mcset nl Close Schließen
#mcset nl Address Adresse
#mcset nl Short-id Kurz-Id
#mcset nl "Input a contact" "Kontakt eingeben"
#mcset nl "Edit contact" "Bearbeite Kontakt"
#mcset nl Mr Herr
#mcset nl Ms Fräulein
#mcset nl Mrs Frau
#mcset nl "Default-as" "Vorbesetzen mit"
#mcset nl "Mobile Phone" Mobiltelefon
#mcset nl Postcode Postleitzahl
#mcset nl Country Land
#mcset nl Note Bemerkung
#mcset nl "Select Actions ..." "Aktionen auswählen ..."
#mcset nl Filename Dateiname
#mcset nl All Alle
#mcset nl Any Beliebig
#mcset nl Unclaimed Unveranlagt
#mcset nl Pending Wartend
#mcset nl Active Aktiv
#mcset nl Blocked Blockiert
#mcset nl Completed Abgeschlossen
#mcset nl Aborted Abgebrochen
#mcset nl "Date Expected" "Erwartetes Datum"
#mcset nl Tomorrow Morgen
#mcset nl Later Später
#mcset nl Earlier Früher
#mcset nl "Show Fields" "Felder anzeigen"
#mcset nl "Due Date" "Fälligkeitsdatum"
#mcset nl Refresh Aktualisieren
#mcset nl "Sort by" "Sortieren nach"
#mcset nl "Actions view of" "Aktionen, Sicht von:"
#mcset nl "Save Action History As ..." "Speichere Aktions-Historie unter..."
#mcset nl "Action history" "Historie für Aktion"
#mcset nl Revise Ändern
#mcset nl History Historie
#mcset nl Duration Dauer
#mcset nl "Total duration" Gesamtdauer
#mcset nl "Save Actions Display As ..." "Speichere Aktionsanzeige unter ..."
#mcset nl "Save Log View Display As ..." "Speichere Log-Anzeige unter ..."
#mcset nl "Select Log Files ..." "Auswahl von Log-Dateien"
#mcset nl "Log view" "Log-Anzeige"
#mcset nl "Edit Preferences" "Bearbeite Einstellungen"
#mcset nl Displayed Angezeigt:
#mcset nl "Total expected time" "Gesamte erwartete Zeit:"
#mcset nl unknown unbekannt
#mcset nl "Pick an action to move from" "Wechsel des Status einer Aktion von"
#mcset nl to nach
#mcset nl "Refresh Active" "Liste der aktiven Akt. neu aufbauen"
#mcset nl "Active Time Blocked" "Aktiviere fällige Aktionen"
#mcset nl "Archive Old Actions" "Archiviere alte Aktionen"
#mcset nl colleague Kollege
#mcset nl customer Kunde
#mcset nl supplier Lieferant
#mcset nl contact Kontakt
#mcset nl friend Privat
#mcset nl "Interruptions Report" "Unterbrechungen"
#mcset nl "There were a total of" "Es gibt insgesamt"
#mcset nl "interruptions in" "Unterbrechungen in"
#mcset nl "days." "Tagen."
#mcset nl "The average number of interruptions in a day was" "Die durchschnittliche Anzahl von Unterbrechungen pro Tag war"
#mcset nl "The peak number of interruptions per day was" "Die Spitzen-Anzahl von Unterbrechungen pro Tag war"
#mcset nl "vCard Files" "vCard Dateien"
#mcset nl " vCard files to Import" " Zu importierende vCard Dateien"
#mcset nl "Introduction" "Einführung"
#mcset nl "Hints" "Hinweise"
#mcset nl "Actions overrun" "Überschreitung der geplanten Zeiten"
#mcset nl "Actions not completed" "Aktivitäten nicht beendet"
#mcset nl "Interruptions" "Unterbrechungen"
#mcset nl "Progress from" "Fortschritt von"
#mcset nl " to " " bis "
#mcset nl "Achievements" "Erreichtes"
#mcset nl "Tasks completed since last report" "Seit letztem Bericht erledigte Aufgaben"
#mcset nl "Expected" "Erwartet"
#mcset nl "Actual" "Tatsächlich"
#mcset nl "Tasks started since last report" "Seit letztem Bericht gestartete Aufgaben"
#mcset nl "Tasks slipped since last report" "Aufgaben, die die Zeit überschreiten werden"
#mcset nl "Active tasks" "Aktive Aufgaben"
#mcset nl "Scheduled" "Geplant"
#mcset nl "Forecast" "Prognose"
#mcset nl "Completion" "Erledigung"
#mcset nl "Delegated-to" "Delegiert an"
#mcset nl "Delegated" "Delegiert"
#mcset nl "delegated" "delegiert"
#mcset nl "Pick" "Auswahl"
#mcset nl "Update" "Aktualisierung"
#mcset nl "meeting-preparation" "Besprechungsvorbereitung"
#mcset nl "meeting" "Besprechung"
#mcset nl "email" "EMail"
