./" Manual page for taglog
.TH tag 1 "2001-11-7"
.SH NAME
taglog \- Time Management and Recording system
.SH SYNOPSIS
.B taglog

.SH DESCRIPTION

Taglog allows you to keep an online daybook, recording what you have done,
and to plan your future actions. It produces reports on how your time
was spent.

For further information see the tutorial, and the built in help.

.SH AUTHOR
John Lines (john@paladin.demon.co.uk)

