#

namespace import -force msgcat::mcset

mcset de Help Hilfe
mcset de Cancel Abbruch
mcset de Quit Abbruch
mcset de Exit Ende
mcset de Next Weiter
mcset de Action Aktion
mcset de Actions Aktionen 
mcset de actions Aktionen
mcset de Reports Berichte
mcset de Preferences Einstellungen
mcset de Open... Öffnen
mcset de Pause Anhalten
mcset de Resume Fortfahren
mcset de {Add/Edit Log} {Log Hinzufügen/Ändern}
mcset de Add... Hinzufügen...
mcset de View Ansicht
mcset de Complete Abschließen
mcset de Activate Aktivieren
mcset de {Abort Active} {Abbruch Aktiv}
mcset de {Abort Pending} {Abbruch Wartend}
mcset de Abort Abbrechen
mcset de Reactivate Reaktivieren
mcset de Projects Projekte
mcset de Add Hinzufügen
mcset de Edit Bearbeiten
mcset de About Über
mcset de {Please select the date of log} {Bitte das Datum für Logeinträge auswählen,}
mcset de {entries to be input or edited} {die bearbeitet oder neu eingegeben werden sollen}
mcset de {Input and editing of log entries} {Eingabe und Bearbeitung von Logeinträgen}
mcset de "Log edit" Log-Bearbeitung
mcset de "Date selection" "Datumauswahl"
mcset de "No date selected" "Kein Datum ausgewählt"
mcset de "Invalid date format" "Ungültiges Datumsformat"
mcset de "Editing of log file" "Bearbeitung einer Log-Datei"
mcset de Day Tag
mcset de day Tag
mcset de days Tage
mcset de week Woche
mcset de "Import of log entries" "Import von Logeinträgen"
mcset de File Datei
mcset de {No entries found in file} {Keine Einträge gefunden in Datei}
mcset de "Import all" "Alles"
mcset de Import Importieren
mcset de Project Projekt
mcset de "End " Ende
mcset de End Ende
mcset de Delete Löschen
mcset de "Edit log entry" "Bearbeitung eines Log-Eintrages"
mcset de "Add a new entry" "Neuer Log-Eintrag"
mcset de {Start Time} Startzeit
mcset de {End Time} Ende
mcset de {ActionTitle} {Titel der Aktion}
mcset de Activity Aktivität
mcset de Contact Kontakt
mcset de Contacts Kontakte
mcset de Save Speichern
mcset de "Save As..." "Speichern unter..."
mcset de Description Beschreibung
mcset de "Adjust to previous EndTime" "Zeit an vorheriges Ende anpassen"
mcset de "Adjust to following Startime" "An nächste Startzeit anpassen"
mcset de "Invalid date range" "Zeitbereich ungültig"
mcset de "The StartTime is greater\nthan the EndTime" "Startzeit größer als Endzeit"
mcset de "Invalid date" "Ungültiges Datum"
mcset de {Please enter a value for} {Bitte einen Wert eingeben für:}
mcset de {is not a valid\ntime value for} {ist keine gültige\nZeit für Tag}
mcset de "There are overlapping (marked with '>')\nand inconsistent (marked with '!') time ranges." "Es existieren überlappende ('>')\nund inkonsistente '(!)' Zeitbereiche."
mcset de "There are overlapping time ranges (marked with '>')." "Es existieren überlappende Zeitbereiche."
mcset de "There are inconsistent time ranges (marked with '!')." "Es existieren inkonsistente Zeitbereiche."
mcset de {Do you want to save?} {Wollen Sie trotzdem abspeichern?}
mcset de "Weekly time bookings by project" "Projekte: Wöchentliche Zeitbuchungen"
mcset de "Time by activity" "Gesamtzeit je Aktivität"
mcset de "Total time for a project" "Gesamtzeit für ein Projekt"
mcset de "Project Progress Report" "Projektfortschritt"
mcset de Directory Verzeichnis
mcset de "Current Directory" "Aktuelles Verzeichnis"
mcset de "File name :" "Dateiname:"
mcset de "Save Text" "Speichern als Text"
mcset de "Save HTML" "Speichern als HTML"
mcset de "Save HTML..." "Speichern als HTML ..."
mcset de "Description contains" "Beschreibung enthält"
mcset de "Documentation Directory" "Dokumentationsverzeichnis"
mcset de "Data directory root" "Wurzelverzeichnis für Daten"
mcset de Language Sprache
mcset de "Hours Worked per Day (decimal)" "Arbeitsstunden pro Tag (dezimal)"
mcset de "Date Format" Datumsformat
mcset de "European (DD/MM/YYYY)" "Europäisch (DD/MM/YYYY)"
mcset de "American (MM/DD/YYYY)" "Amerikanisch (MM/DD/YYYY)"
mcset de "History Window Depth" {Zeilen für Historien-Fenster}
mcset de "Current Window Depth" "Zeilen für Log-Fenster"
mcset de "Number of 'Today' actions" "Anzahl der 'Heute'-Aktionen"
mcset de Prefix Präfix
mcset de "SMTP Preferences filename" "Dateiname für SMTP-Einstellungen"
mcset de "email address" "EMail-Adresse"
mcset de traditional traditionell
mcset de "local mail submission port" "lokaler Mail-Port"
mcset de "Input an action" "Eingabe einer Aktion"
mcset de {Edit action} "Bearbeite Aktion"
mcset de Title Titel
mcset de Date Datum
mcset de Priority Priorität
mcset de Expected-cost "Erwartete Kosten"
mcset de Expected-time "Erwartete Zeit"
mcset de Expected-Time "Erwartete Zeit"
mcset de Revised-expected-time "Geänd. Erwartete Zeit"
mcset de Expected-start-date "Erwartete Startzeit"
mcset de Completed-date "Fertigstellungsdatum"
mcset de Active-date "Aktivierungsdatum"
mcset de Aborted-date "Abbruchdatum"
mcset de Expected-completed-date "Erw-Fertigstellungsdatum"
mcset de Expected-Completed-Date "Erw-Fertigstellungsdatum"
mcset de Revised-expected-completed-date "Geänd. Erw-Fertigstellungsdatum"
mcset de Revised-date Geänd-Datum
mcset de Precursor Vorgänger
mcset de Active-after "Aktiv nach"
mcset de Subtask-of "Unteraufgabe von"
mcset de Next-action "Nächste Aktion"
mcset de Abort-action Abbruch-Aktion
mcset de Difficulty Schwierigkeit
mcset de nobrainer simpel
mcset de trivial trivial
mcset de easy leicht
mcset de tricky anspruchsvoll
mcset de hard schwer
mcset de "very hard" "sehr schwer"
mcset de Email-status-to "Sende-Status an"
mcset de Deliverable Auslieferbar
mcset de Reason Grund
mcset de Message Nachricht
mcset de "Mail to" "Sende an"
mcset de "Mail an action" "Sende eine Aktion"
mcset de "Add a new project" "Neues Projekt"
mcset de "Project name" Projektname
mcset de "Book as breaks" "Als Pause buchen"
mcset de "Book as overheads" "Als Overhead buchen"
mcset de "Booking Code" "Buchungs-Code"
mcset de "Start Date" "Startdatum"
mcset de "End Date" "Beendigungsdatum"
mcset de "Edit Projects" "Projekte bearbeiten"
mcset de Breaks Pausen
mcset de "Project Times" Projektzeiten
mcset de Total Gesamt
mcset de "Total (non breaks)" "Gesamt (ohne Pausen)"
mcset de Today Heute
mcset de "Select date range" "Zeitbereich"
mcset de "Enter Project details" Projektdetails
mcset de "Enter information for Project Progress Report" "Projektfortschritt"
mcset de "Select Time Period" "Auswahl der Zeitbereichs"
mcset de "Time Format" Zeitformat
mcset de "Decimal hours" "Stunden dezimal"
mcset de "Decimal days" "Tage dezimal"
mcset de "Spread overhead projects" "Overhead Projekte aufteilen"
mcset de "Book by Project" "Sortieren nach Projekt"
mcset de Year Jahr
mcset de weeks Wochen
mcset de "starting at number" "Start bei"
mcset de "Time by Activity" "Gesamtzeit je Aktivität"
mcset de "Project Progress Report for" "Projektfortschrittsbericht für"
mcset de "Total Times for" "Gesamtzeit für"
mcset de "Time Bookings" "Zeitbuchungen"
mcset de Sun "So "
mcset de Mon "Mo "
mcset de Tue "Di "
mcset de Wed "Mi "
mcset de Thu "Do "
mcset de Fri "Fr "
mcset de Sat "Sa "
mcset de "Breaks total" "Pausen gesamt"
mcset de "Time Bookings for week" "Zeitbuchungen für Kalenderwoche"
mcset de  of von
mcset de "Warning - cant open" "Warnung - folgende Datei kann nicht geöffnet werden:" 
mcset de "Total time" Gesamtzeit
mcset de "Total time for" "Die Gesamtzeit für"
mcset de is ist
mcset de "decimal days" "dezimale Tage"
mcset de Examined "Untersucht wurden"
mcset de "files and found entries for" "Dateien. Gefunden wurden Einträge für"
mcset de "of them" "von ihnen"
mcset de "First date was" "Erstes Datum:"
mcset de "last date was" "Letztes Datum:"
mcset de "Adjust start time" "Startzeit anpassen" 
mcset de "Adjust start time back towards previous start time of" "Startzeit anpassen in Richtung auf vorherige Startzeit von"
mcset de "Adjust start time back towards the start of the day" "Startzeit an Tagesbeginn anpassen"
mcset de "Adjust previous end time" "Vorherige End-Zeit anpassen"
mcset de "New Start Time" "Neue Startzeit"
mcset de "Minutes to Subtract from StartTime" "Zu subtrahierende Minuten"
mcset de Set "Startzeit setzen"
mcset de calendar Kalender
mcset de Calendar Kalender
mcset de Su So
mcset de Tu Di
mcset de We Mi
mcset de Th Do
mcset de January Januar
mcset de February Februar
mcset de March März
mcset de April April
mcset de May Mai
mcset de June Juni
mcset de July Juli
mcset de August August
mcset de September September
mcset de October Oktober
mcset de November November
mcset de December Dezember
mcset de "Select Contacts to view" "Auswahl zum Anzeigen von Kontakten"
mcset de Forename Vorname
mcset de Phone Telefon
mcset de Type Typ
mcset de Surname Nachname
mcset de "Contacts Display" "Anzeige der Kontakte"
mcset de Close Schließen
mcset de Address Adresse
mcset de Short-id Kurz-Id
mcset de "Input a contact" "Kontakt eingeben"
mcset de "Edit contact" "Bearbeite Kontakt"
mcset de Mr Herr
mcset de Ms Fräulein
mcset de Mrs Frau
mcset de "Default-as" "Vorbesetzen mit"
mcset de "Mobile Phone" Mobiltelefon
mcset de Postcode Postleitzahl
mcset de Country Land
mcset de Note Bemerkung
mcset de "Select Actions ..." "Aktionen auswählen ..."
mcset de Filename Dateiname
mcset de All Alle
mcset de Any Beliebig
mcset de Unclaimed Unveranlagt
mcset de Pending Wartend
mcset de Active Aktiv
mcset de Blocked Blockiert
mcset de Completed Abgeschlossen
mcset de Aborted Abgebrochen
mcset de "Date Expected" "Erwartetes Datum"
mcset de Tomorrow Morgen
mcset de Later Später
mcset de Earlier Früher
mcset de "Show Fields" "Felder anzeigen"
mcset de "Due Date" "Fälligkeitsdatum"
mcset de Refresh Aktualisieren
mcset de "Sort by" "Sortieren nach"
mcset de "Actions view of" "Aktionen, Sicht von:"
mcset de "Save Action History As ..." "Speichere Aktions-Historie unter..."
mcset de "Action history" "Historie für Aktion"
mcset de Revise Ändern
mcset de History Historie
mcset de Duration Dauer
mcset de "Total duration" Gesamtdauer
mcset de "Save Actions Display As ..." "Speichere Aktionsanzeige unter ..."
mcset de "Save Log View Display As ..." "Speichere Log-Anzeige unter ..."
mcset de "Select Log Files ..." "Auswahl von Log-Dateien"
mcset de "Log view" "Log-Anzeige"
mcset de "Edit Preferences" "Bearbeite Einstellungen"
mcset de Displayed Angezeigt:
mcset de "Total expected time" "Gesamte erwartete Zeit:"
mcset de unknown unbekannt
mcset de "Pick an action to move from" "Wechsel des Status einer Aktion von"
mcset de to nach
mcset de "Refresh Active" "Liste der aktiven Akt. neu aufbauen"
mcset de "Active Time Blocked" "Aktiviere fällige Aktionen"
mcset de "Archive Old Actions" "Archiviere alte Aktionen"
mcset de colleague Kollege
mcset de customer Kunde
mcset de supplier Lieferant
mcset de contact Kontakt
mcset de friend Privat
mcset de "Interruptions Report" "Unterbrechungen"
mcset de "There were a total of" "Es gibt insgesamt"
mcset de "interruptions in" "Unterbrechungen in"
mcset de "days." "Tagen."
mcset de "The average number of interruptions in a day was" "Die durchschnittliche Anzahl von Unterbrechungen pro Tag war"
mcset de "The peak number of interruptions per day was" "Die Spitzen-Anzahl von Unterbrechungen pro Tag war"
mcset de "vCard Files" "vCard Dateien"
mcset de " vCard files to Import" " Zu importierende vCard Dateien"
mcset de "Introduction" "Einführung"
mcset de "Hints" "Hinweise"
mcset de "Actions overrun" "Überschreitung der geplanten Zeiten"
mcset de "Actions not completed" "Aktivitäten nicht beendet"
mcset de "Interruptions" "Unterbrechungen"
mcset de "Progress from" "Fortschritt von"
mcset de " to " " bis "
mcset de "Achievements" "Erreichtes"
mcset de "Tasks completed since last report" "Seit letztem Bericht erledigte Aufgaben"
mcset de "Expected" "Erwartet"
mcset de "Actual" "Tatsächlich"
mcset de "Tasks started since last report" "Seit letztem Bericht gestartete Aufgaben"
mcset de "Tasks slipped since last report" "Aufgaben, die die Zeit überschreiten werden"
mcset de "Active tasks" "Aktive Aufgaben"
mcset de "Scheduled" "Geplant"
mcset de "Forecast" "Prognose"
mcset de "Completion" "Erledigung"
mcset de "Delegated-to" "Delegiert an"
mcset de "Delegated" "Delegiert"
mcset de "delegated" "delegiert"
mcset de "Pick" "Auswahl"
mcset de "Update" "Aktualisierung"
mcset de "meeting-preparation" "Besprechungsvorbereitung"
mcset de "meeting" "Besprechung"
mcset de "email" "EMail"
