#

namespace import -force msgcat::mcset

mcset fr Help Aide
#mcset fr Cancel Abbruch
mcset fr Quit Stoppé
mcset fr Exit Sortie
#mcset fr Next Weiter
#mcset fr Action Aktion
#mcset fr Actions Aktionen 
#mcset fr actions Aktionen
#mcset fr Reports Berichte
mcset fr Preferences Préférences
#mcset fr Open... Öffnen
#mcset fr Pause Anhalten
#mcset fr Resume Fortfahren
#mcset fr {Add/Edit Log} {Log Hinzufügen/Ändern}
#mcset fr Add... Hinzufügen...
#mcset fr View Ansicht
#mcset fr Complete Abschließen
#mcset fr Activate Aktivieren
#mcset fr {Abort Active} {Abbruch Aktiv}
#mcset fr {Abort Pending} {Abbruch Wartend}
#mcset fr Abort Abbrechen
#mcset fr Reactivate Reaktivieren
#mcset fr Projects Projekte
#mcset fr Add Hinzufügen
#mcset fr Edit Bearbeiten
#mcset fr About Über
#mcset fr {Please select the date of log} {Bitte das Datum für Logeinträge auswählen,}
#mcset fr {entries to be input or edited} {die bearbeitet oder neu eingegeben werden sollen}
#mcset fr {Input and editing of log entries} {Eingabe und Bearbeitung von Logeinträgen}
#mcset fr "Log edit" Log-Bearbeitung
#mcset fr "Date selection" "Datumauswahl"
#mcset fr "No date selected" "Kein Datum ausgewählt"
#mcset fr "Invalid date format" "Ungültiges Datumsformat"
#mcset fr "Editing of log file" "Bearbeitung einer Log-Datei"
mcset fr Day Jour
mcset fr day jour
mcset fr days jours
#mcset fr week Woche
#mcset fr "Import of log entries" "Import von Logeinträgen"
#mcset fr File Datei
#mcset fr {No entries found in file} {Keine Einträge gefunden in Datei}
#mcset fr "Import all" "Alles"
#mcset fr Import Importieren
#mcset fr Project Projekt
#mcset fr "End " Ende
#mcset fr End Ende
#mcset fr Delete Löschen
#mcset fr "Edit log entry" "Bearbeitung eines Log-Eintrages"
#mcset fr "Add a new entry" "Neuer Log-Eintrag"
#mcset fr {Start Time} Startzeit
#mcset fr {End Time} Ende
#mcset fr {ActionTitle} {Titel der Aktion}
#mcset fr Activity Aktivität
#mcset fr Contact Kontakt
#mcset fr Contacts Kontakte
#mcset fr Save Speichern
#mcset fr "Save As..." "Speichern unter..."
#mcset fr Description Beschreibung
#mcset fr "Adjust to previous EndTime" "Zeit an vorheriges Ende anpassen"
#mcset fr "Adjust to following Startime" "An nächste Startzeit anpassen"
#mcset fr "Invalid date range" "Zeitbereich ungültig"
#mcset fr "The StartTime is greater\nthan the EndTime" "Startzeit größer als Endzeit"
#mcset fr "Invalid date" "Ungültiges Datum"
#mcset fr {Please enter a value for} {Bitte einen Wert eingeben für:}
#mcset fr {is not a valid\ntime value for} {ist keine gültige\nZeit für Tag}
#mcset fr "There are overlapping (marked with '>')\nand inconsistent (marked with '!') time ranges." "Es existieren überlappende ('>')\nund inkonsistente '(!)' Zeitbereiche."
#mcset fr "There are overlapping time ranges (marked with '>')." "Es existieren überlappende Zeitbereiche."
#mcset fr "There are inconsistent time ranges (marked with '!')." "Es existieren inkonsistente Zeitbereiche."
#mcset fr {Do you want to save?} {Wollen Sie trotzdem abspeichern?}
#mcset fr "Weekly time bookings by project" "Projekte: Wöchentliche Zeitbuchungen"
#mcset fr "Time by activity" "Gesamtzeit je Aktivität"
#mcset fr "Total time for a project" "Gesamtzeit für ein Projekt"
#mcset fr "Project Progress Report" "Projektfortschritt"
#mcset fr Directory Verzeichnis
#mcset fr "Current Directory" "Aktuelles Verzeichnis"
#mcset fr "File name :" "Dateiname:"
#mcset fr "Save Text" "Speichern als Text"
#mcset fr "Save HTML" "Speichern als HTML"
#mcset fr "Save HTML..." "Speichern als HTML ..."
#mcset fr "Description contains" "Beschreibung enthält"
#mcset fr "Documentation Directory" "Dokumentationsverzeichnis"
#mcset fr "Data directory root" "Wurzelverzeichnis für Daten"
#mcset fr Language Sprache
#mcset fr "Hours Worked per Day (decimal)" "Arbeitsstunden pro Tag (dezimal)"
#mcset fr "Date Format" Datumsformat
#mcset fr "European (DD/MM/YYYY)" "Europäisch (DD/MM/YYYY)"
#mcset fr "American (MM/DD/YYYY)" "Amerikanisch (MM/DD/YYYY)"
#mcset fr "History Window Depth" {Zeilen für Historien-Fenster}
#mcset fr "Current Window Depth" "Zeilen für Log-Fenster"
#mcset fr "Number of 'Today' actions" "Anzahl der 'Heute'-Aktionen"
#mcset fr Prefix Präfix
#mcset fr "SMTP Preferences filename" "Dateiname für SMTP-Einstellungen"
#mcset fr "email address" "EMail-Adresse"
#mcset fr traditional traditionell
#mcset fr "local mail submission port" "lokaler Mail-Port"
#mcset fr "Input an action" "Eingabe einer Aktion"
#mcset fr {Edit action} "Bearbeite Aktion"
#mcset fr Title Titel
#mcset fr Date Datum
#mcset fr Priority Priorität
#mcset fr Expected-cost "Erwartete Kosten"
#mcset fr Expected-time "Erwartete Zeit"
#mcset fr Expected-Time "Erwartete Zeit"
#mcset fr Revised-expected-time "Geänd. Erwartete Zeit"
#mcset fr Expected-start-date "Erwartete Startzeit"
#mcset fr Completed-date "Fertigstellungsdatum"
#mcset fr Active-date "Aktivierungsdatum"
#mcset fr Aborted-date "Abbruchdatum"
#mcset fr Expected-completed-date "Erw-Fertigstellungsdatum"
#mcset fr Expected-Completed-Date "Erw-Fertigstellungsdatum"
#mcset fr Revised-expected-completed-date "Geänd. Erw-Fertigstellungsdatum"
#mcset fr Revised-date Geänd-Datum
#mcset fr Precursor Vorgänger
#mcset fr Active-after "Aktiv nach"
#mcset fr Subtask-of "Unteraufgabe von"
#mcset fr Next-action "Nächste Aktion"
#mcset fr Abort-action Abbruch-Aktion
#mcset fr Difficulty Schwierigkeit
#mcset fr nobrainer simpel
#mcset fr trivial trivial
#mcset fr easy leicht
#mcset fr tricky anspruchsvoll
#mcset fr hard schwer
#mcset fr "very hard" "sehr schwer"
#mcset fr Email-status-to "Sende-Status an"
#mcset fr Deliverable Auslieferbar
#mcset fr Reason Grund
#mcset fr Message Nachricht
#mcset fr "Mail to" "Sende an"
#mcset fr "Mail an action" "Sende eine Aktion"
#mcset fr "Add a new project" "Neues Projekt"
#mcset fr "Project name" Projektname
#mcset fr "Book as breaks" "Als Pause buchen"
#mcset fr "Book as overheads" "Als Overhead buchen"
#mcset fr "Booking Code" "Buchungs-Code"
#mcset fr "Start Date" "Startdatum"
#mcset fr "End Date" "Beendigungsdatum"
#mcset fr "Edit Projects" "Projekte bearbeiten"
#mcset fr Breaks Pausen
#mcset fr "Project Times" Projektzeiten
#mcset fr Total Gesamt
#mcset fr "Total (non breaks)" "Gesamt (ohne Pausen)"
#mcset fr Today Heute
#mcset fr "Select date range" "Zeitbereich"
#mcset fr "Enter Project details" Projektdetails
#mcset fr "Enter information for Project Progress Report" "Projektfortschritt"
#mcset fr "Select Time Period" "Auswahl der Zeitbereichs"
#mcset fr "Time Format" Zeitformat
#mcset fr "Decimal hours" "Stunden dezimal"
#mcset fr "Decimal days" "Tage dezimal"
#mcset fr "Spread overhead projects" "Overhead Projekte aufteilen"
#mcset fr "Book by Project" "Sortieren nach Projekt"
#mcset fr Year Jahr
#mcset fr weeks Wochen
#mcset fr "starting at number" "Start bei"
#mcset fr "Time by Activity" "Gesamtzeit je Aktivität"
#mcset fr "Project Progress Report for" "Projektfortschrittsbericht für"
#mcset fr "Total Times for" "Gesamtzeit für"
#mcset fr "Time Bookings" "Zeitbuchungen"
mcset fr Sun "Dim"
mcset fr Mon "Lun"
mcset fr Tue "Mar"
mcset fr Wed "Mer"
mcset fr Thu "Jeu"
mcset fr Fri "Ven"
mcset fr Sat "Sam"
#mcset fr "Breaks total" "Pausen gesamt"
#mcset fr "Time Bookings for week" "Zeitbuchungen für Kalenderwoche"
#mcset fr  of von
#mcset fr "Warning - cant open" "Warnung - folgende Datei kann nicht geöffnet werden:" 
#mcset fr "Total time" Gesamtzeit
#mcset fr "Total time for" "Die Gesamtzeit für"
#mcset fr is ist
#mcset fr "decimal days" "dezimale Tage"
#mcset fr Examined "Untersucht wurden"
#mcset fr "files and found entries for" "Dateien. Gefunden wurden Einträge für"
#mcset fr "of them" "von ihnen"
#mcset fr "First date was" "Erstes Datum:"
#mcset fr "last date was" "Letztes Datum:"
#mcset fr "Adjust start time" "Startzeit anpassen" 
#mcset fr "Adjust start time back towards previous start time of" "Startzeit anpassen in Richtung auf vorherige Startzeit von"
#mcset fr "Adjust start time back towards the start of the day" "Startzeit an Tagesbeginn anpassen"
#mcset fr "Adjust previous end time" "Vorherige End-Zeit anpassen"
#mcset fr "New Start Time" "Neue Startzeit"
#mcset fr "Minutes to Subtract from StartTime" "Zu subtrahierende Minuten"
#mcset fr Set "Startzeit setzen"
#mcset fr calendar Kalender
#mcset fr Calendar Kalender
#mcset fr Su So
#mcset fr Tu Di
#mcset fr We Mi
#mcset fr Th Do
#mcset fr January Januar
#mcset fr February Februar
#mcset fr March März
#mcset fr April April
#mcset fr May Mai
#mcset fr June Juni
#mcset fr July Juli
#mcset fr August August
#mcset fr September September
#mcset fr October Oktober
#mcset fr November November
#mcset fr December Dezember
#mcset fr "Select Contacts to view" "Auswahl zum Anzeigen von Kontakten"
#mcset fr Forename Vorname
#mcset fr Phone Telefon
#mcset fr Type Typ
#mcset fr Surname Nachname
#mcset fr "Contacts Display" "Anzeige der Kontakte"
#mcset fr Close Schließen
#mcset fr Address Adresse
#mcset fr Short-id Kurz-Id
#mcset fr "Input a contact" "Kontakt eingeben"
#mcset fr "Edit contact" "Bearbeite Kontakt"
#mcset fr Mr Herr
#mcset fr Ms Fräulein
#mcset fr Mrs Frau
#mcset fr "Default-as" "Vorbesetzen mit"
#mcset fr "Mobile Phone" Mobiltelefon
#mcset fr Postcode Postleitzahl
#mcset fr Country Land
#mcset fr Note Bemerkung
#mcset fr "Select Actions ..." "Aktionen auswählen ..."
#mcset fr Filename Dateiname
#mcset fr All Alle
#mcset fr Any Beliebig
#mcset fr Unclaimed Unveranlagt
#mcset fr Pending Wartend
#mcset fr Active Aktiv
#mcset fr Blocked Blockiert
#mcset fr Completed Abgeschlossen
#mcset fr Aborted Abgebrochen
#mcset fr "Date Expected" "Erwartetes Datum"
#mcset fr Tomorrow Morgen
#mcset fr Later Später
#mcset fr Earlier Früher
#mcset fr "Show Fields" "Felder anzeigen"
#mcset fr "Due Date" "Fälligkeitsdatum"
#mcset fr Refresh Aktualisieren
#mcset fr "Sort by" "Sortieren nach"
#mcset fr "Actions view of" "Aktionen, Sicht von:"
#mcset fr "Save Action History As ..." "Speichere Aktions-Historie unter..."
#mcset fr "Action history" "Historie für Aktion"
#mcset fr Revise Ändern
#mcset fr History Historie
#mcset fr Duration Dauer
#mcset fr "Total duration" Gesamtdauer
#mcset fr "Save Actions Display As ..." "Speichere Aktionsanzeige unter ..."
#mcset fr "Save Log View Display As ..." "Speichere Log-Anzeige unter ..."
#mcset fr "Select Log Files ..." "Auswahl von Log-Dateien"
#mcset fr "Log view" "Log-Anzeige"
#mcset fr "Edit Preferences" "Bearbeite Einstellungen"
#mcset fr Displayed Angezeigt:
#mcset fr "Total expected time" "Gesamte erwartete Zeit:"
#mcset fr unknown unbekannt
#mcset fr "Pick an action to move from" "Wechsel des Status einer Aktion von"
#mcset fr to nach
#mcset fr "Refresh Active" "Liste der aktiven Akt. neu aufbauen"
#mcset fr "Active Time Blocked" "Aktiviere fällige Aktionen"
#mcset fr "Archive Old Actions" "Archiviere alte Aktionen"
#mcset fr colleague Kollege
#mcset fr customer Kunde
#mcset fr supplier Lieferant
#mcset fr contact Kontakt
#mcset fr friend Privat
#mcset fr "Interruptions Report" "Unterbrechungen"
#mcset fr "There were a total of" "Es gibt insgesamt"
#mcset fr "interruptions in" "Unterbrechungen in"
#mcset fr "days." "Tagen."
#mcset fr "The average number of interruptions in a day was" "Die durchschnittliche Anzahl von Unterbrechungen pro Tag war"
#mcset fr "The peak number of interruptions per day was" "Die Spitzen-Anzahl von Unterbrechungen pro Tag war"
#mcset fr "vCard Files" "vCard Dateien"
#mcset fr " vCard files to Import" " Zu importierende vCard Dateien"
#mcset fr "Introduction" "Einführung"
#mcset fr "Hints" "Hinweise"
#mcset fr "Actions overrun" "Überschreitung der geplanten Zeiten"
#mcset fr "Actions not completed" "Aktivitäten nicht beendet"
#mcset fr "Interruptions" "Unterbrechungen"
#mcset fr "Progress from" "Fortschritt von"
#mcset fr " to " " bis "
#mcset fr "Achievements" "Erreichtes"
#mcset fr "Tasks completed since last report" "Seit letztem Bericht erledigte Aufgaben"
#mcset fr "Expected" "Erwartet"
#mcset fr "Actual" "Tatsächlich"
#mcset fr "Tasks started since last report" "Seit letztem Bericht gestartete Aufgaben"
#mcset fr "Tasks slipped since last report" "Aufgaben, die die Zeit überschreiten werden"
#mcset fr "Active tasks" "Aktive Aufgaben"
#mcset fr "Scheduled" "Geplant"
#mcset fr "Forecast" "Prognose"
#mcset fr "Completion" "Erledigung"
#mcset fr "Delegated-to" "Delegiert an"
#mcset fr "Delegated" "Delegiert"
#mcset fr "delegated" "delegiert"
#mcset fr "Pick" "Auswahl"
#mcset fr "Update" "Aktualisierung"
#mcset fr "meeting-preparation" "Besprechungsvorbereitung"
#mcset fr "meeting" "Besprechung"
#mcset fr "email" "EMail"
